import type { Metadata } from "next";
import "./globals.css";
// import NavBar from "@/components/NavBar";
import FloatingMenu from "@/components/FloatingMenu";
import Header from "@/components/Header";
import CompassGuide from "@/components/CompassGuide";
// import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className="flex flex-col min-h-screen bg-white text-black">
        {/* <NavBar /> */}
        <Header />
        <main className="flex-grow">{children}</main>
        <CompassGuide />
        <FloatingMenu />
        {/* <Footer /> */}
      </body>
    </html>
  );
}
